# Generated by Django 4.1 on 2022-08-05 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_person_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birthday',
            new_name='creation_date',
        ),
    ]
