# Generated by Django 4.1 on 2022-08-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_rename_birthday_person_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
